[package]
name = "sublime_fuzzy"
version = "0.7.0"
authors = ["Benedikt Schatz <schlchtwtrfrnt@gmail.com>"]
description = "Fuzzy matching algorithm based on Sublime Text's string search."
repository = "https://github.com/Schlechtwetterfront/fuzzy-rs"
readme = "README.md"
keywords = ["fuzzy", "match", "search", "text"]
categories = ["text-processing", "algorithms"]
license-file = "LICENSE"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "sfz"
path = "src/main.rs"

[dependencies]
bumpalo = { version = "3.19.0", features = ["collections"] }
serde = { version = "1", features = ["derive"], optional = true }

[features]
serde = ["dep:serde"]
